name: Ionic

on: [pull_request, workflow_dispatch]

defaults:
  run:
    working-directory: question_app
jobs:
  ionic:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 14, 16, 18 ]
    name: Node ${{ matrix.node }} sample    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '${{ matrix.node }}'
          cache: 'npm'
          cache-dependency-path: question_app/package-lock.json
      - run: npm install
      - run: npm run lint
      - run: npm run build